# Generated by Django 3.2.9 on 2021-11-29 12:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objectiva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default='The activity will surely be a success', max_length=100000),
        ),
        migrations.AddField(
            model_name='activity',
            name='endingTime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='notificationMode',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='startingTime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
