# Generated by Django 3.2.9 on 2021-12-04 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objectiva', '0002_auto_20211129_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='activityName',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(default='These activity will surely be a success', max_length=100000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notificationMode',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='activity_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(default='none ', max_length=200)),
                ('description', models.TextField(default='These activity will surely be a success', max_length=100000)),
                ('notificationMode', models.IntegerField(default=1)),
                ('complete', models.BooleanField()),
                ('activity', models.ForeignKey(default='none ', on_delete=django.db.models.deletion.CASCADE, to='objectiva.activity')),
            ],
        ),
    ]
