# Generated by Django 3.2.9 on 2021-12-04 19:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objectiva', '0003_auto_20211204_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notificationMode',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity_name',
            name='notificationMode',
            field=models.IntegerField(default=False),
        ),
    ]
