# Generated by Django 3.2.9 on 2021-12-04 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objectiva', '0004_auto_20211204_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_name',
            old_name='activity',
            new_name='Activity',
        ),
        migrations.RemoveField(
            model_name='activity_name',
            name='activityName',
        ),
        migrations.RemoveField(
            model_name='activity_name',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity_name',
            name='notificationMode',
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity_name',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
