# Generated by Django 3.2.9 on 2021-12-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectiva', '0005_auto_20211205_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endingTime',
            field=models.DateTimeField(blank=True, default='2021-12-05 23:09:37', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startingTime',
            field=models.DateTimeField(blank=True, default='2021-12-05 23:09:37', null=True),
        ),
    ]
