# Generated by Django 3.2.9 on 2021-12-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectiva', '0007_auto_20211205_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endingTime',
            field=models.DateTimeField(),
        ),
    ]
